<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>DuanEcommerce</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\common\domain\DuanEcommerce.Domain\DuanEcommerce.Domain.csproj" />
    <ProjectReference Include="..\DuanEcommerce.TestBase\DuanEcommerce.TestBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
